### ISSUE TITLE
Request for release

### ISSUE THREAD

**Issue by bchretien** [gbiggs/rtshell#26]
Hi,

While packaging rtshell for Arch Linux, I noticed that most of the problems I had were actually solved on master after the last release (e.g. #19, 821c6f476f5bcaa9117f054b34e89cca518cb9f6). If you think this is the right time, would it be possible to have a 3.0.2 release?

**Comment by gbiggs** [comment]
4.0.0 has been due for ages anyway, so I released that.

**Comment by bchretien** [comment]
Great, thanks!
