### ISSUE TITLE
test_too_many_targets (test_cmds.rtconTests) inadequate?

### ISSUE THREAD

**Issue by yosuke** [gbiggs/rtshell#34]
I think the rtcon command call like
```
rtcon Std0.rtc:out Out0.rtc:in C10.rtc:in
```
Is allowed and it means "connect Std0.rtc:out to Out0.rtc:in and C10.rtc:in".

That case, the test test_too_many_targets (test_cmds.rtconTests) may be inadequate.

If it is not allowed, I can add error message to rtcon.

**Comment by gbiggs** [comment]
Yes, that rtcon command should be allowed. A connection can have any number of ports, even just one. rtcon needs to allow this.

**Comment by yosuke** [comment]
Good to know.

Fixed the test in.

https://github.com/yosuke/rtshell/commit/017249881bb3453210a570edd2bbda140af5be22
