### ISSUE TITLE
rtshell error 「CORBA.MARSHEL」　

### ISSUE THREAD

**Issue by Kengo-Ishida** [gbiggs/rtshell#40]
rtact: CORBA.MARSHAL(omniORB.MARSHAL_InvalidEnumValue, CORBA.COMPLETED_YES)
rtact: CORBA.MARSHAL(omniORB.MARSHAL_InvalidEnumValue, CORBA.COMPLETED_YES)

**Comment by kenichi-ohara** [comment]
I'm so sorry for my student's questions.
We could solve our problem by ourselves.
