### ISSUE TITLE
rtcon: Values instance has no attribute 'no_duplicates'

### ISSUE THREAD

**Issue by win-katami** [gbiggs/rtshell#41]
When a port is connected using rtcon, an error occurs, and it can't be connected.

    $ rtcon ./localhost/ConsoleIn0.rtc:out ./localhost/ConsoleOut0.rtc:in
    rtcon: Values instance has no attribute 'no_duplicates'

I think it occurs by influence of an added option '-d'.

When it's changed as follows, an error disappears.

    +++ rtcon.py  2017-07-05 13:27:36.950912051 +0900
    @@ -86,7 +86,7 @@
     
         conn_name = options.name if options.name else None
    
    -    if options.no_duplicates:
    +    if options.no_dups:
             for p in port_objs:
                 if p.get_connection_by_name(conn_name):
                     raise rts_exceptions.DuplicateConnectionNameError(conn_name,

**Comment by gbiggs** [comment]
Fixed by #42
